/**
 * This class represents a Computer player of the reversi game.
 * 
 * @author Aaron Martinez    <ajm21935@uga.edu>
 * @author Matt Butcher    <mab48671@uga.edu>
 *
 */
public abstract class ComputerPlayer extends Player {	
	
	/**
	 * Halts gameplay for 2.5 seconds to simulate that the computer
	 * is making a decision.
	 */
    public void delay(){
    	    
    	System.out.print("Computer Player \'" + this.myPiece + "\' turn");
    	
    	for(int i = 0; i < 5; i++) {
    		
    		System.out.print(". ");
    		
	    	try {
	    		Thread.sleep(500);
	    	}//try
	    	catch(InterruptedException ie) {
	    		Thread.currentThread().interrupt();
	    	}//catch
    	}
    	System.out.println();
    }//delay
    
    /**
     * Commits a move on the game board. The move is either defined by 
     * a person, randomly generated by the computer, or selected by an 
     * algorithm depending on the object using the method.
     * @return String
     * 				String contains the row and column divided by a space.
     */
    public abstract String move();
    
}//ComputerPlayer